### PR TITLE
Port bobbing behavior from Half-Life 2 over

### PR DESCRIPTION
**Pull request by reductor**
This ports over the HL2 bobbing behavior, most of it comes straight from [CBaseHLCombatWeapon::CalcViewmodelBob](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/shared/hl2/basehlcombatweapon_shared.cpp#L256) and [CBaseHLCombatWeapon::AddViewmodelBob](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/shared/hl2/basehlcombatweapon_shared.cpp#L331), additional context can also be gained from [CBaseViewModel::CalcViewModelView](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/baseviewmodel_shared.cpp#L385) which gets the bobing values from weapons.

HL2 had bobbing behavior defined on weapons but nothing in the default HL implementation actually implemented any of this, so I didn't port this over to HL2.

Additionally some minor refactors and cleanups in this to make it a bit easier to reason about `V_CalcNormalRefdef` which is quiet a beast of a function.

### CODE REVIEW

**Comment by sabianroberts** [comment]
I’ll clone your fork and check this out when I get on my PC later. Thank you!! :D

**Review by sabianroberts — CHANGES_REQUESTED** [review]
a.) In Half-Life 2, the screen does not move when walking around
b.) In-game, the weapon viewmodel does not swing around like in HL2

**Comment by reductor** [comment]
@barney-heatwave thanks for pointing this out, I did this on a laptop with only a track pad and no copy of HL2 installed, so was unable to fully test it or compare it with actual HL2. I just grabbed a copy of HL2 on my desktop PC to validate it against

I had applied the bob to the camera view instead of the view model, this has now been changed to update the view model.

**Comment by sabianroberts** [comment]
Giving this a build now, gonna see how this looks.

**Review by sabianroberts — CHANGES_REQUESTED** [review]
@ReDucTor There's still just one more teeny change to make, and that's how the weapon ViewModel swings around when you look around.

Video demo: https://youtu.be/jElU1mD8JnI?t=1231

**Comment by sabianroberts** [comment]
The actual name of the swinging thing the viewmodel does is Viewmodel Lag. You can find references to it here in the Source 2013 SDK:
image

**Comment by sabianroberts** [comment]
More info:
image

**Comment by sabianroberts** [comment]
Addition: When I merge this PR, there will be a conflict due to commits I've made to view.cpp. This can be easily resolved.

**Comment by sabianroberts** [comment]
@ReDucTor I've tried it myself and seen other developers on TWHL talk about it and to conclude, ViewModel sway might be a bit too much; so I've decided to go without it. I will now resolve the conflict and merge the PR. Congrats, you're now a Phoenix Developer!

**Comment by reductor** [comment]
Good to hear, gun model lag is separate from bobbing anyway.

**Comment by sabianroberts** [comment]
> Good to hear, gun model lag is separate from bobbing anyway.

You should get an invite to have push access to this repository soon; so if you still want to work on the ViewModel lag, you're very welcome to.

**Pull request merged**
